mainpage/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, include
from mainpage import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ask/', views.AskView.as_view(), name='ask'),
    path('question/id/<int:qid>', views.QuestionView.as_view(), name='question_by_id'),
    path('question/<slug:slug>', views.QuestionView.as_view(), name='question_by_slug'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(next_page='mainpage:index'), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('vote/', views.vote, name='vote'),
    path('answer/<int:aid>/mark_correct/', views.mark_correct, name='mark_correct'),
]

vibecode_forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/forms.py
from django import forms
from mainpage.models import Question, Answer, User
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'detailed']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'detailed': forms.Textarea(attrs={'placeholder': 'Your question'}),
        }
        error_messages = {
            'title': {'required': 'You must enter the title.'},
            'detailed': {'required': 'You must enter your question.'},
            'tags_text': {'You must enter at least one tag.'}
        }

    
    tags_text = forms.CharField(
        label='Tags',
        required=True,
        error_messages={'required': 'You must enter at least one tag.'},
        widget=forms.TextInput(attrs={'placeholder': 'Tags (e.g. golang, docker, kubernetes)'}),
        )
    
    def clean_title(self):
        title = self.cleaned_data.get('title').strip()
        if not title:
            raise forms.ValidationError('You must enter the title.')
        return title

    def clean_detailed(self):
        detailed = self.cleaned_data.get('detailed').strip()
        if not detailed:
            raise forms.ValidationError('You must enter your question.')
        return detailed
    
    def clean_tags_text(self):
        tags_text = self.cleaned_data.get('tags_text')
        tags = [t.strip() for t in tags_text.replace(';', ',').replace(' ', '').split(',') if t.strip()] # Заменяем все `;` на `,` и убираем пробелы чтобы по запятым разделить теги. Потом делим строку tags_text по запятым на подстроки(теги). Проходимся по тегам, если строка пустая, то скип, если нет, то норм.
        if not tags:
            raise forms.ValidationError('You must enter at least one tag.')
        return tags


class SettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'avatar']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Login'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'avatar': forms.FileInput(attrs={'accept': 'image/*'}),
        }
        error_messages = {
            'username': {'required': 'You must enter login.'},
            'email': {'required': 'You must enter email.'},
        }
    
    
    def clean_username(self):
        new_username = self.cleaned_data.get('username')

        if self.instance.pk and new_username:
            if User.objects.filter(username=new_username).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('This login is already taken by another user.')
        return new_username
    
    def clean_email(self):
        new_email = self.cleaned_data.get('email')

        if self.instance.pk and new_email:
            if User.objects.filter(username=new_email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('This email is already taken by another user.')
        return new_email

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar')
        if avatar and avatar.size > 4 * 1024 * 1024: # 4Мб
            raise forms.ValidationError("Too big file (max size is 4Mb).")
        return avatar


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': 'Email'})
    )

    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )

    password2 = forms.CharField(
        label='Repeat password',
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Repeat your password'})
    )


    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', )
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Login'}),
        }
        error_messages = {
            'username': {'required': 'You must enter login.'},
            'password1': {'required': 'You must enter password.'},
            'password2': {'required': 'You must confirm your password.'},
            'email': {'required': 'You must enter email.'},
        }
    

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if username and User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError('This login is already taken by another user.')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email__iexact=email).exists():
                raise forms.ValidationError('This email is already taken by another user.')
        return email
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The two password fields didn't match.")
        
        if password1:
            try:
                password_validation.validate_password(password1, user=None)
            except forms.ValidationError as e:
                raise forms.ValidationError(e.message)
        
        return password2

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text',]
        widgets = {
            'answer_text': forms.Textarea(attrs={'placeholder': 'Your answer'}),
        }
        error_messages = {
            'answer_text': {'required': 'You must enter your answer.'},
        }

    def clean_answer_text(self):
        answer_text = self.cleaned_data.get('answer_text').strip()
        if not answer_text:
            raise forms.ValidationError('You must enter your answer.')
        return answer_text

mainpage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponseForbidden, Http404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.db.models import Q

from mainpage.forms import QuestionForm, SettingsForm, RegistrationForm, AnswerForm
from mainpage.models import Question, Answer, Tag, User
from mainpage.mixins import TagsAndMembersMixin
from mainpage.utilts import toggle_vote

import math


@login_required
@require_POST
def vote(request):
    target = request.POST.get('target')
    
    try:
        obj_id = int(request.POST.get('id'))
        value = int(request.POST.get('value'))
    except (TypeError, ValueError):
        return redirect(request.META.get('HTTP_REFERER', '/'))

    if value not in (1, -1):
        return redirect(request.META.get('HTTP_REFERER', '/'))
    
    if target == 'question':
        obj = get_object_or_404(Question, id=obj_id)
    elif target == 'answer':
        obj = get_object_or_404(Answer, id=obj_id)
    else:
        return redirect(request.META.get('HTTP_REFERER', '/'))
    
    toggle_vote(request.user, obj, value)
    return redirect(request.META.get('HTTP_REFERER', '/'))

@login_required
@require_POST
def mark_correct(request, aid):
    answer = get_object_or_404(Answer, pk=aid)
    question = answer.question

    if not (request.user == question.author or request.user.is_superuser):
        return HttpResponseForbidden("Only question author or superuser can mark answers.")

    is_checked = 'is_correct' in request.POST

    answer.is_correct = is_checked
    answer.save(update_fields=['is_correct'])

    return redirect(request.META.get('HTTP_REFERER', '/'))


class IndexView(TagsAndMembersMixin, TemplateView):
    http_method_names = [ 'get', ]
    template_name = 'mainpage/index.html'
    QUESTIONS_PER_PAGE = 4

    def get_questions(self, tag = None, user = None, search = None):
        question = Question.objects.all()
        if tag:
            tag_obj = Tag.objects.filter(slug=tag).first()
            if tag_obj:
                question = question.filter(tags=tag_obj)
        if user:
            question = question.filter(author=user)
        
        if search:
            words = search.split()
            for word in words:
                question = question.filter(
                    Q(slug__icontains=word) |
                    Q(title__icontains=word) |
                    Q(detailed__icontains=word) |
                    Q(author__username__icontains=word) |
                    Q(tags__slug__icontains=word)
                ).distinct()
        
        return question

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs) 

        tag = self.request.GET.get('tag', None)
        author_slug = self.request.GET.get('author', None)
        author = None
        if author_slug:
            author = User.objects.filter(slug=author_slug).first()
        
        search_query = self.request.GET.get('search', '').strip()
        questions = self.get_questions(tag=tag, user=author, search=search_query).order_by('-id')
        context['search_query'] = search_query
        context['count_questions'] = questions.count()
        context['questions_per_page'] = self.QUESTIONS_PER_PAGE
        context['max_page'] = math.ceil(questions.count() / self.QUESTIONS_PER_PAGE)
        if context['max_page'] <= 0: context['max_page'] = 1

        page = self.request.GET.get('page', 1)
        try: # Защищаемся от выхода за предел страниц и ввод строки
            page = int(page)
            if page < 1:
                page = 1
            elif page > context['max_page']:
                page = context['max_page']
        except:
            page = 1
        context['page'] = page

        # Вычисляем номера страниц, которые нужно показывать
        # Вроде максимально просто сделал
        if context['max_page'] < 6:
            context['pages'] = [i for i in range(1, context['max_page'] + 1)]
        elif page < 4:
            context['pages'] = [i for i in range(1, 5)] + [context['max_page']]
        elif page > (context['max_page'] - 3):
            context['pages'] = [1] + [i for i in range(context['max_page'] - 3, context['max_page'] + 1)]
        else: 
            context['pages'] = [1] + [i for i in range(page - 1, page + 2)] + [context['max_page']]

        if page == 1:
            context["new_questions"] = questions[0:self.QUESTIONS_PER_PAGE]
        else:
            context["new_questions"] = questions[(page - 1) * self.QUESTIONS_PER_PAGE:((page - 1) * self.QUESTIONS_PER_PAGE) + self.QUESTIONS_PER_PAGE]

        # Временная затычка, выводим первые 20 тегов и пользователей
        context['tags_list'], context['members_list'] = self.get_tags_and_members()[:20]

        return context
    
    
    def dispatch(self, request, *args, **kwargs):
        print(request)
        return super(IndexView, self).dispatch(request, *args, **kwargs)
    


class AskView(TagsAndMembersMixin, LoginRequiredMixin, FormView):
    http_method_names = [ 'get', 'post', ]
    template_name = 'mainpage/ask.html'
    form_class = QuestionForm
    success_url = reverse_lazy('mainpage:index')

    def form_valid(self, form):
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()

        tags_list = form.cleaned_data['tags_text']
        tag_objs = []
        for t in tags_list:
            tag_obj, _ = Tag.objects.get_or_create(title=t.strip().lower())
            tag_objs.append(tag_obj)
        question.tags.set(tag_objs)

        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(AskView, self).get_context_data(**kwargs)
        context['tags_list'], context['members_list'] = self.get_tags_and_members()
        return context
    
    def dispatch(self, request, *args, **kwargs):
        print(request)
        return super(AskView, self).dispatch(request, *args, **kwargs)


class SettingsView(TagsAndMembersMixin, LoginRequiredMixin, FormView):
    http_method_names = [ 'get', 'post']
    template_name = 'mainpage/settings.html'
    form_class = SettingsForm
    success_url = reverse_lazy('mainpage:settings')

    def get_form_kwargs(self): # для заполнения полей инфой о текущем пользователе
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.request.user
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
            kwargs['files'] = self.request.FILES
        return kwargs
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        context['tags_list'], context['members_list'] = self.get_tags_and_members()
        return context
    
    def dispatch(self, request, *args, **kwargs):
        print(request)
        return super(SettingsView, self).dispatch(request, *args, **kwargs)
    

class QuestionView(TagsAndMembersMixin, FormView):
    http_method_names = [ 'get', 'post' ]
    template_name = 'mainpage/question.html'
    form_class = AnswerForm
    success_url = reverse_lazy('')
    ANSWERS_PER_PAGE = 4

    def get_object(self):
        slug = self.kwargs.get('slug')
        qid = self.kwargs.get('qid')
        
        if slug:
            question = Question.objects.filter(slug=slug).first()
            if question:
                return question
        
        elif qid > 0:
            return get_object_or_404(Question, pk=qid)
        
        raise Http404("Question not found")

    def get_context_data(self, **kwargs):
        context = super(QuestionView, self).get_context_data(**kwargs)
        question = self.get_object()

        context['question'] = question
        context['question_rating'] = question.rating
        context['user_vote_question'] = question.get_user_vote(self.request.user)

        answers = question.answer_set.select_related('author').all()
        # сортируем от лучших ответов к худшим
        context['answers'] = sorted([(ans, ans.get_user_vote(self.request.user), ans.rating) for ans in answers], key=lambda x: x[2], reverse=True)

        context['count_answers'] = answers.count()
        context['answers_per_page'] = self.ANSWERS_PER_PAGE
        context['max_page'] = math.ceil(answers.count() / self.ANSWERS_PER_PAGE)
        if context['max_page'] <= 0: context['max_page'] = 1

        page = self.request.GET.get('page', 1)
        try:
            page = int(page)
            if page < 1:
                page = 1
            elif page > context['max_page']:
                page = context['max_page']
        except:
            page = 1
        context['page'] = page

        if context['max_page'] < 6:
            context['pages'] = [i for i in range(1, context['max_page'] + 1)]
        elif page < 4:
            context['pages'] = [i for i in range(1, 5)] + [context['max_page']]
        elif page > (context['max_page'] - 3):
            context['pages'] = [1] + [i for i in range(context['max_page'] - 3, context['max_page'] + 1)]
        else: 
            context['pages'] = [1] + [i for i in range(page - 1, page + 2)] + [context['max_page']]

        if page == 1:

mainpage/templates/mainpage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'images/site-avatar.png' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <div class="logo">
            <a class="logo-link" href="{% url 'mainpage:index' %}">
                <img class="site-avatar" src="{% static 'images/site-avatar.png' %}" alt="Логотип сайта Ask Eldar">
                <p class="site-name">Ask Eldar</p>
            </a>
        </div>

        <div class="search" role="search">
            <form action="/" method="get" class="search-form">
                <img class="search-icon" src="{% static 'images/loupe-icon.png' %}" alt="Иконка поиска">
                <input type="text" name="search" placeholder="Search...">
                <button type="submit" class="search-button">ASK!</button>
            </form>
        </div>

        <div class="profile">
            {% if user.is_authenticated %}
                <div id="authorized">
                    {% if user.avatar %}
                        <img class="user-avatar" src="{{ user.avatar.url }}" alt="Аватар пользователя">
                    {% else %}
                        <img class="user-avatar" src="{% static 'images/default-avatar.png' %}" alt="Аватар пользователя">
                    {% endif %}
                    <div class="user-info">
                        <p class="username">{{ user.username }}</p>
                        <div class="user-links">
                            <a type="button" href="{% url 'mainpage:settings' %}">Settings</a>
                            <form action="{% url 'mainpage:logout' %}" method="post" class="logout-form">
                                {% csrf_token %}
                                <button type="submit" class="logout-button">Log out</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% else %}
                <div id="not-authorized">
                    <a type="button" class="login-button" href="{% url 'mainpage:login' %}">Log in</a>
                    <a type="button" class="signup-button" href="{% url 'mainpage:registration' %}">Sign up</a>
                </div>
                
            {% endif %}
        </div>
    </header>
    <main>
        <div class="main-container">
            {% block content %}{% endblock %}
        </div>

        <aside>
            <div class="offers">
                <div class="popular-tags">
                    <h1>Popular tags</h1>
                    <nav>
                        <ul class="tags">
                            {% for tag in tags_list %}
                                <li class="tag">
                                    <a href="/?tag={{ tag.slug }}" class="{{ tag.color }}">{{ tag.title }}</a>
                                </li>
                            {% empty %}
                                <li>No tags</li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
                <div class="best-members">
                    <h1>Best members</h1>
                    <nav>
                        <ul class="members">
                            {% for member in members_list %}
                                <li class="member">
                                    <a href="/?author={{ member.slug }}" class="{{ member.color }}">{{ member.username }}</a>
                                </li>
                            {% empty %}
                                <li>No members</li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
            </div>
        </aside>
    </main>
</body>

mainpage/templates/mainpage/index.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
    <h1>
        Newest Questions
        <a href="{% url 'mainpage:ask' %}">Ask your question!</a>
        <!-- <span><a href="#">Hot Questions</a></span> -->
    </h1>
    <div class="questions-list">
        {% for question in new_questions %}
            <div class="question">
                <div class="question-data">
                    {% if question.author.avatar %}
                        <img class="question-user-avatar" src="{{ question.author.avatar.url }}" alt="Аватар автора вопроса">
                    {% else %}
                        <img class="question-user-avatar" src="{% static 'images/default-avatar.png' %}" alt="Аватар автора вопроса">
                    {% endif %}
                    <div class="question-text">
                        <a href="/question/{{ question.slug }}">{{ question.title }}</a>
                        <p>{{ question.detailed }}</p>
                    </div>
                </div>
                <div class="question-info">
                    <div class="votes-answers">
                        <p>{{ question.answers_count }} answers</p>
                        <p>{{ question.rating }} votes</p>
                    </div>
                    <div class="question-tags">
                        <p class="tags-header">Tags:&nbsp;</p>
                        <ul class="tags-list">
                            {% for tag in question.get_tags %}
                            <li><a href="/?tag={{ tag.title }}">{{ tag.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="pagination">
    {% for page in pages %}
        <a href="?page={{ page }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if request.GET.author %}&author={{ request.GET.author }}{% endif %}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ page }}</a>
    {% endfor %}
</div>
<div class="white-block"></div>
{% endblock %}

mainpage/templates/mainpage/login.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<h1>Log In</h1>
{% if form.errors %}
<div type="error" class="login-error">
    <p>Wrong username or password.</p>
</div>
{% endif %}
<form method="post" action="{% url 'mainpage:login' %}" class="login-form">
    {% csrf_token %}
    <div class="login">
        <p>Login</p>
        <input type="login-input" name="username" placeholder="Login" required>
    </div>
    <div class="password">
        <p>Password</p>
        <input type="password" name="password" placeholder="Password" required>
    </div>
    <button type="submit" class="login-button">Log in</button>
    <a href="{% url 'mainpage:registration' %}" class="create-new-account-link">Create new account</a>
</form>
{% endblock %}

mainpage/templates/mainpage/question.html
{% extends "mainpage/base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/question.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
    <div class="current-question">
        <div class="avatar-and-counter-block"> <!--я не знаю, как этот блок по нормальному назвать. Это буквально блок для аватарки и счётчика рейтинга-->
            {% if question.author.avatar %}
                <img class="question-user-avatar" src="{{ question.author.avatar.url }}" alt="Аватар автора вопроса">
            {% else %}
                <img class="question-user-avatar" src="{% static 'images/default-avatar.png' %}" alt="Аватар автора вопроса">
            {% endif %}
            <div class="counter">
                <p class="count">{{ question_rating }}</p>
                <div class="rating-buttons">
                    {% if user.is_authenticated %}
                        <form action="{% url 'mainpage:vote' %}" method="post" class="button-form">
                            {% csrf_token %}
                            <input type="hidden" name="target" value="question">
                            <input type="hidden" name="id" value="{{ question.id }}">
                            <button type="submit" name="value" value="1" class="rating-increase {% if user_vote_question == 1 %}active{% endif %}"></button>
                        </form>
                        
                        <form action="{% url 'mainpage:vote' %}" method="post" class="button-form">
                            {% csrf_token %}
                            <input type="hidden" name="target" value="question">
                            <input type="hidden" name="id" value="{{ question.id }}">
                            <button type="submit" name="value" value="-1" class="rating-decrease {% if user_vote_question == -1 %}active{% endif %}"></button>
                        </form>
                    {% else %}
                        <button class="rating-increase"></button>
                        <button class="rating-decrease"></button>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="question-data">
            <p class="question-title">{{ question.title }}</p>
            <p class="question-text">{{ question.detailed }}</p>
            <div class="question-tags">
                <p>Tags:&nbsp</p>
                <ul class="tags-list">
                {% for tag in question.get_tags %}
                    <li><a href="/?tag={{ tag.title }}">{{ tag.title }}</a></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="answers">
        {% for answer, user_vote, answer_rating in best_answers %}
            <div class="answer">
                <div class="answer-avatar-and-counter-block">
                    {% if answer.author.avatar %}
                        <img class="answer-user-avatar" src="{{ answer.author.avatar.url }}" alt="Аватар автора ответа">
                    {% else %}
                        <img class="answer-user-avatar" src="{% static 'images/default-avatar.png' %}" alt="Аватар автора ответа">
                    {% endif %}
                    <div class="answer-counter">
                        <p class="answer-count">{{ answer_rating }}</p>
                        <div class="answer-rating-buttons">
                            {% if user.is_authenticated %}
                                <form action="{% url 'mainpage:vote' %}" method="post" class="button-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="target" value="answer">
                                    <input type="hidden" name="id" value="{{ answer.id }}">
                                    <button type="submit" name="value" value="1" class="answer-rating-increase {% if user_vote == 1 %}active{% endif %}"></button>
                                </form>

                                <form action="{% url 'mainpage:vote' %}" method="post" class="button-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="target" value="answer">
                                    <input type="hidden" name="id" value="{{ answer.id }}">
                                    <button type="submit" name="value" value="-1" class="answer-rating-decrease {% if user_vote == -1 %}active{% endif %}"></button>
                                </form>
                            {% else %}
                                <button class="answer-rating-increase"></button>
                                <button class="answer-rating-decrease"></button>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="answer-data">
                    <p class="answer-text">{{ answer.answer_text }}</p>
                    <form method="post" action="{% url 'mainpage:mark_correct' aid=answer.id %}">
                        {% csrf_token %}
                        <input id="correct-{{ forloop.counter }}" type="checkbox" name="is_correct"
                            {% if answer.is_correct %}checked{% endif %}
                            {% if request.user != question.author and not request.user.is_superuser %}disabled{% endif %}
                            onchange="this.form.submit()">
                        <label for="correct-{{ forloop.counter }}">Correct!</label>
                    </form>
                </div>
            </div>
        {% endfor %}
        
        <div class="pagination">
            {% for page in pages %}
                <a href="?page={{ page }}">{{ page }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="enter-answer">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.answer_text }}
            {% if form.answer_text.errors %}
                <div class="textarea-error">
                    <p>{{ form.answer_text.errors.0 }}</p>
                </div>
            {% endif %}
            </div>
            <button type="submit" class="answer-button">ANSWER!</button>
        </form>
    </div>
</div>
{% endblock %}